/* MTI_DPI */

/*
 * Copyright 2002-2019 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
add_pxl_to_client_buff_mono(
    int r,
    int g,
    int b,
    int pos);

DPI_LINK_DECL DPI_DLLESPEC
int
client_close();

DPI_LINK_DECL DPI_DLLESPEC
int
client_connect();

DPI_LINK_DECL DPI_DLLESPEC
int
client_send();

#endif 
